Ревизия протокола 1.15 Closes #16
MoreliaTalk/morelia_protocol pull request #17
Opened 2020-09-05 20:02 UTC by stepanskryabin

- добавлен метод add_flow, all_flow.
- добавлены ошибки с кодом 409, 520.
- оптимизированы все методы, исключена лишняя информация отправляемая в запросах/ответах.
- исправлено описание полей JSON-объекта.
- удалён reply_to из объекта message.
- удалён username из объекта from_user.
- удалён type из объекта from_flow.
- в описание объекта user добалены поля salt, key.
- подкорректирована логика работы методов register_user и authentification.
- в запрос метода register_user добавлены salt, key.
- теперь итерируемость данных в полях flow, message, user зависит от метода.
- прочие мелкие правки.

2020-09-07 16:01 UTC, NekrodNIK requested changes
Название протокола не подходит. Я предлагаю MoreliaTalk API.

2020-09-08 08:42 UTC, NekrodNIK reviewed
Метод get_update должен возвращать **только** сообщения

2020-09-08 09:00 UTC, stepanskryabin commented
> Метод get_update должен возвращать **только** сообщения

для этого есть метод all_message

2020-09-10 11:15 UTC, Hazzari approved these changes

2020-09-10 13:40 UTC, NekrodNIK approved these changes
OK

2020-09-10 18:51 UTC, rus-ai approved these changes
На мой взгляд все готово к запуску. Наверное и на этом стоит остановиться и реализовать то что есть.

2020-09-11 05:18 UTC, stepanskryabin commented
Ревизия протокола 1.15

2020-09-11 05:19 UTC, merged